authors/urls.py
from django.shortcuts import render
from django.urls import path
from . import views

app_namee = 'authors'

urlpatterns = [
    path('register/', views.AuthorView.as_view(), name='author-register')
]

task/urls.py
from django.urls import path
from . import views

app_name = "task"

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('task/slug:/<slug:slug>/', views.TaskView.as_view(), name='task-view'),
    path('new_task/', views.NewTaskView.as_view(), name='new-task')
]

task_manager/urls.py
from xml.etree.ElementInclude import include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
    path('authors/', include('authors.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, documnet_root=settings.STATIC_ROOT)

authors/models.py
from django.db import models

# Create your models here.

task/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here.
class Category(models.Model):
    categoria = models.CharField(max_length=200, verbose_name='Categoria')
    class Meta:
        verbose_name_plural = 'Categorias'
    def __str__(self):
        return self.categoria

DEPARTAMENTO = (
    (0,"Gestão_Arquivo"),
    (1,"Processamento_Salário"),
    (2,"Organização_Agenda"),
    (3,"Controle_Inventário"),
   
)


class Task(models.Model):
      title = models.CharField(max_length=200)
      description = models.TextField()
      completed = models.BooleanField(default=False)
      slug = models.SlugField(unique=True)
      time_completed = models.DateTimeField(auto_now_add=True)    
      author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
      )
      category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True
      )

      def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

      class Meta:
        verbose_name_plural = 'Tasks'
      def __str__(self):
            return self.title

authors/forms.py
from django import forms
from django.contrib.auth.models import User


class RegisterForm(forms.ModelForm):
      class Meta:
        model = User
        fields = [
              'first_name',
              'last_name',
              'username',
                  'email',
                  'password',
                  ] 

task/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Enviar'))

authors/views.py
from django.http import Http404
from django.shortcuts import render
from django.views.generic import TemplateView
from .forms import RegisterForm

# Create your views here.
class AuthorView(TemplateView):
     template_name = 'authors/pages/register.html'

     def get_context_data(self, **kwargs):
          context = super().get_context_data(**kwargs)

          context.update({
               'register_form': RegisterForm(),
          })   

          return context  
     
     def post(self, request, *args, **kwargs):
          register_form = RegisterForm(request.POST)
          
          if register_form.is_valid():
                 register_form.save()
                 # Armazena os dados do formulário na sessão
                 request.session['register_form_data'] = register_form.cleaned_data
                    
                 # Você pode redirecionar ou retornar uma resposta apropriada aqui
                 return self.get(request, *args, **kwargs)

          else:
                raise Http404()
          
          return self.get(request, *args, **kwargs)

task/views.py
from typing import Any
from django.shortcuts import get_object_or_404, render
from django.views.generic import TemplateView, DetailView
from .models import Task
from .forms import TaskForm
# Create your views here.


class Home(TemplateView):
      template_name = 'task/pages/index.html'

      def get_context_data(self, **kwargs):
          context = super().get_context_data(**kwargs)
          task = Task.objects.filter(completed=True).order_by('-id')

          context.update({
               'task': task,
          })

          return context

class TaskView(DetailView):
     modal = Task
     template_name = 'task/pages/task_view.html'
     context_objects_name = 'task'

     def get_object(self, queryset=None):
          return get_object_or_404(Task, slug=self.kwargs.get('slug'), completed=True)
     
     def get_context_data(self, **kwargs):
         context = super().get_context_data(**kwargs)
         context["tasks_recentes"] = Task.objects.filter(completed=True).order_by('-id')
         return context

class NewTaskView(TemplateView):
     template_name = 'task/pages/new_task.html'

     def get_context_data(self, **kwargs):
          context = super().get_context_data(**kwargs)
          task = Task.objects.filter(completed=True).order_by('-id')

          context.update({
               'task': task,
               'task_form': TaskForm(),
          })

          return context
     
     def post(self, request, *args, **kwargs):
          task_form = TaskForm(request.POST)
          
          if task_form.is_valid():
               task_form.save()

          return self.get(request, *args, **kwargs)

authors/templates/authors/pages/register.html
{% extends "base.html" %}

{% block title %} Register  | {% endblock title %}


{% block content %}

<div class="container mt-3">
     <div class="row justify-content-center">
       <h1 class="text-center">Register {{ request.sesseion.number }} </h1>
     </div>

     <div class="row justify-content-center">
          <form  action="" method="POST" class="row g-3 needs-validation" novalidat>
            {% csrf_token %}
            <div class="col-md-4 form-content form-content-grid position-relative">
              {% for field in register_form %} 
                <div class="form-group">
                    <label for="{{ field.id_for_label }}" class="form-label"> {{ field.label }} </label>
                    {{ field }}

                    {% if field.help_text %}
                      <p class="hepl-text"> {{ field.help_text }} </p>
                    {% endif %} 

                    {{ field.errors }}  
                </div>
              {% endfor %} 
            </div> 
            <div class="form-content form-content-grid">
              <div class="col-12 form-group">
                <button class="btn btn-primary" type="submit">Submit</button>
              </div>
            </div>
          </form>
    </div> 
</div>

{% endblock content %}

task/templates/task/pages/index.html
{% extends "base.html" %}

{% block title %} | Home {% endblock title %}

{% block content %}
     {% include "task/partials/header.html" %}
     {% include "task/partials/task_list.html" %}
{% endblock content %}

task/templates/task/pages/new_task.html
{% extends "base.html" %}



{% block title %} | Home {% endblock title %}

{% block content %}
{% include "task/partials/header.html" %}
     <div class="container">
      <form action="" class="row p-lg-4 gy-2 mb-0" method="post">
            {% csrf_token %}
              <div class="col-12">
                  <h2 style="font-family: "Barlow", sans-serif !important;">Created new Task</h2>

              </div>
              <div class="col-12">
                 <div class="border-top border-primary w-40 mx-auto juntos-content-center mb-4"></div>
              </div>
              <div class="col-lg-6">
                  <input type="text" name="title" class="form-control" id="exampleFormControlInput1" placeholder="title" required>
              </div>
              <div class="col-lg-6">
                  <input type="text" name="slug" class="form-control" id="exampleFormControlInput1" placeholder="slug" required>
             </div>
             <div class="col-lg-6">
                  <input type="text" name="slug" class="form-control" id="exampleFormControlInput1" placeholder="slug" required>
             </div>
             <div class="col-12 mb-3">
                 <textarea name="description" id=""  class="form-control" placeholder="description of the new Task" required></textarea>
             </div>
             <div class="col-12">
                 <button type="submit" name="enviar" class="btn btn-primary">Create</button>
             </div>
          </form>
     </div>
{% endblock content %}

task/templates/task/pages/task_view.html
{% extends "base.html" %}

{% block title %} | Home {% endblock title %}

{% block content %}

     {% include "task/partials/header.html" %}

     <section class="mb-3">
      <div class="container mt-5">
        <div class="row justify-content-beteween mt-3">
            <div class="grid text-center">
                  <div class="g-col-4 ">   
                                      <div class="card" style="width: 25rem;">
                                          <div class="card-body">
                                            <h2 class="card-title">{{ task.title }}</h2>
                                            <p class="card-text">{{ task.description }}</p>
                                            <p class="card-text"> finish an {{ task.time_completed|date:"H:i"}}</p>
                                            <p class="card-category"> Category {{ task.category}}</p>
                                            <p class="card-author">by: {{ task.author.first_name}} {{ task.author.last_name}}</p>
                                            <a href="" class="btn btn-danger">Delete</a>
                                            <a href="" class="btn btn-primary">Edit</a>
                                          </div>
                                        </div>     
                  </div>
                </div>
        </div>
      </div>
     </section>
     

   
{% endblock content %}

task/templates/task/partials/body.html
{% load static %}


<script src="{% static 'task/js/bootstrap.bundle.min.js' %} "></script>


    
</body>
</html>

task/templates/task/partials/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static 'task/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'task/css/bootstrap.min.css' %}">

</head>

task/templates/task/partials/header.html
{% load static %}


<nav class="navbar navbar-expand-lg bg-primary">
      <div class="container">
        <a class="navbar-brand text-light" href="{% url "task:home" %}">TASKS OF ADM</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
          <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
            <li class="nav-item">
              <a class="nav-link active text-light" aria-current="page" href="{% url "task:home" %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url "task:new-task" %}">New Task</a>
            </li>
          </ul>
        </div>
     </div>
</nav>

task/templates/task/partials/task_list.html
{% load static %}


<div class="container mt-5">
     <div class="row justify-content-center g-4 mb-3">
                    {% if task %}
                            {% for t in task %}
                            <div class="col-12 col-md-6 col-lg-4">
                              <div class="card" style="width: 20rem;">
                                  <div class="card-body">
                                    <h2 class="card-title">{{ t.title }}</h2>
                                    <p class="card-text">{{ t.description|slice:":90"}}...</p>
                                    <p class="card-text"> finish an {{ t.time_completed|date:"H:i"}}</p>
                                    <p class="card-category"> Category {{ t.category}}</p>
                                    <p class="card-author">by: {{ t.author.first_name}} {{ t.author.last_name}}</p>
                                    <a href="{% url 'task:task-view' t.slug %}" class="btn btn-primary">see more</a>
                                  </div>
                                </div>
                            </div>
                            {% endfor %}
                    {% else %}
                        <p>Task there is not completed.</p>
                    {% endif %}
     </div>
</div>